#!/bin/sh

ROOTDIR=
CONFDIR=$ROOTDIR/etc/blink1-reminder
PROFILES=$CONFDIR/profile.d


if [ -n "$1" ]; then
    if [ -d "$PROFILES/$1" ]; then
        profile=$1
    else
        for x in "$PROFILES"/*_"$1"; do
            if [ -d "$x" ]; then
                profile=$x
                break
            fi
        done
    fi

    if [ -d "$profile" ]; then
        touch "$profile/timeholder"
        sync
    fi
fi


prog=$(basename "$0")
device_id=

blink1_tool() {
    args=

    if [ -n "$device_serial" ]; then
        if [ -z "$device_id" ]; then
            device_id=$(blink1-tool --list | sed -n "s/^id:\([0-9]\+\) - serialnum:${device_serial}\\b.*$/\1/p" | head -1)

            if [ -z "$device_id" ]; then
                echo "$prog: device not found" >&2
                exit 1
            fi
        fi

        args="$args --id $device_id"
    fi

    blink1-tool $args "$@" >/dev/null
    rc=$?

    if [ "$rc" != 0 ]; then
        echo "$prog: blink1-tool dies with code $rc" >&2
        exit 1
    fi
}


blink1_tool --off

. "$CONFDIR/reminder.conf"


test "$(date +%H%M%S)" -lt "$(echo "$wake_up_time" | tr -d :)00" && exit 0
test "$(date +%H%M%S)" -ge "$(echo "$sleep_time"   | tr -d :)00" && exit 0


i=0

for profile in "$PROFILES"/*; do
    test -e "$profile" || continue
    "$profile/check" && continue

    . "$CONFDIR/default.conf"
    . "$profile/config"

    blink1_tool --rgb "$rgb" --millis "$fading"             --setpattline $((i*4 + 0))
    blink1_tool --rgb "$rgb" --millis "$((delay - fading))" --setpattline $((i*4 + 1))
    blink1_tool --rgb 0,0,0  --millis "$fading"             --setpattline $((i*4 + 2))
    blink1_tool --rgb 0,0,0  --millis "$((delay - fading))" --setpattline $((i*4 + 3))

    i=$((i + 1))
done

if [ "$i" != 0 ]; then
    blink1_tool --play "1,0,$((i*4 - 1)),0"
fi


exit 0
